//
// 请注意：bbsmax 不是一个免费产品，源代码仅限用于学习，禁止用于商业站点或者其他商业用途
// 如果您要将bbsmax用于商业用途，需要从官方购买商业授权，得到授权后可以基于源代码二次开发
//
// 版权所有 厦门麦斯网络科技有限公司
// 公司网站 www.bbsmax.com
//

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Max.Installs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Install_Bin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Install_Bin() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Max.Installs.Install_Bin", typeof(Install_Bin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string _3_0_0_0820 {
            get {
                return ResourceManager.GetString("_3_0_0_0820", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string _3_0_0_0825 {
            get {
                return ResourceManager.GetString("_3_0_0_0825", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --- idmax 升级脚本 ----------------------------------------------------------
        ///IF EXISTS(SELECT * FROM sysconstraints WHERE object_name(sysconstraints.constid)=&apos;FK_System_Max_Advertisements_AdvertisementCatalogs&apos;) BEGIN
        ///	PRINT N&apos;正在删除 [Max_Advertisements] 的外键&apos;
        ///	ALTER TABLE [Max_Advertisements] DROP CONSTRAINT [FK_System_Max_Advertisements_AdvertisementCatalogs]
        ///END
        ///GO
        ///
        ///
        ///IF EXISTS(SELECT * FROM sysconstraints WHERE object_name(sysconstraints.constid)=&apos;FK_System_Max_Faqs_System_Max_FaqCatalogs&apos;) BEGIN
        ///	PRI [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string _3_0_0_0909 {
            get {
                return ResourceManager.GetString("_3_0_0_0909", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --- idmax 升级脚本 ----------------------------------------------------------        ///IF OBJECT_ID ( &apos;Max_LoginUserIPLogs&apos;, &apos;U&apos; ) IS NULL         ///BEGIN        ///CREATE TABLE [Max_LoginUserIPLogs](        ///	[RecordID] [int] IDENTITY(1,1) NOT NULL,        ///	[RecordUserID] [int] NOT NULL,        ///	[RecordUserName] [nvarchar](64) NOT NULL,        ///	[RecordUserNickName] [nvarchar](64) NOT NULL,        ///	[LoginIP] [varchar](15) NOT NULL,        ///	[LoginTime] [datetime] NOT NULL,        ///	[VisitPage] [nvarchar](512) NOT NULL,        /// CONSTRAINT [PK_LoginUserIPLogs] PRIMARY KEY CLUSTERED         ///(        ///	[RecordID] A [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string _3_0_0_1122 {
            get {
                return ResourceManager.GetString("_3_0_0_1122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N&apos;[bbsMax_Identities_4000]&apos;) AND OBJECTPROPERTY(id, N&apos;IsUserTable&apos;) = 1)
        ///	DROP TABLE [bbsMax_Identities_4000]
        ///
        ///
        ///SELECT TOP 4000 ID = IDENTITY(int,1,1) INTO [bbsMax_Identities_4000]
        ///FROM syscolumns a, syscolumns b
        ///ALTER TABLE [bbsMax_Identities_4000] ADD CONSTRAINT PK_bbsMax_Identities_4000 PRIMARY KEY(ID)
        ///
        ///
        ///IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N&apos;[bbsMax_Identities_8000]&apos;) AND OBJECTPROPERTY(id, N&apos;IsUserTable&apos;) = 1) [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string _3_0_0_1127 {
            get {
                return ResourceManager.GetString("_3_0_0_1127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UPDATE [System_Max_Permissions] SET [PermissionItems]=&apos;AllowSignIn:1;AllowManageCommonPermissions:1;AllowManageCommonPermissions_Roles:7;AllowManageManagePermissions:1;AllowManageUsers:1;AllowUpdateUserCurrencies:1;AllowManageRoles:1;AllowManageRoles_Roles:7;AllowManageMedals:1;AllowManageAdvertisements:1;AllowManageCurrencyFields:1;AllowManageDefaultEmoticons:1;AllowManageUserEmoticons:1;AllowManagePostIcons:1;AllowManageExtendedUserProfileFields:1;AllowManageInviteRegisters:1;AllowManageLogsForShow:1;Allo [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string _3_0_0_1201 {
            get {
                return ResourceManager.GetString("_3_0_0_1201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --此文件是 2.3 版本到 3.0.0.0730 的升级脚本(sql server 版)
        ///--编码： utf-8
        ///
        ///
        ///---------------------以下是 idmax 库的升级脚本(邀请码表放在最后处理)
        ///
        ///IF OBJECT_ID ( &apos;Max_ChangePasswordLogs&apos;, &apos;U&apos; ) IS NOT NULL
        ///DROP TABLE [Max_ChangePasswordLogs]
        ///
        ///GO
        ///
        ///IF OBJECT_ID ( &apos;Max_ErrorPasswordLogs&apos;, &apos;U&apos; ) IS NOT NULL
        ///DROP TABLE [Max_ErrorPasswordLogs]
        ///
        ///GO
        ///
        ///IF OBJECT_ID ( &apos;Max_LinkedApplications&apos;, &apos;U&apos; ) IS NOT NULL
        ///DROP TABLE [Max_LinkedApplications]
        ///
        ///GO
        ///
        ///IF OBJECT_ID ( &apos;System_Max_Faqs&apos;, &apos;U&apos; ) IS NOT NULL
        ///DROP TABLE [System_Max_Faqs]        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string _3_0_0730_0000 {
            get {
                return ResourceManager.GetString("_3_0_0730_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///--关闭所有主键插入
        ///
        ///declare @tname varchar(255);
        ///declare @sql varchar(255);
        ///declare dropsql_cursor cursor for
        ///select [name] FROM sysobjects WHERE [type] = &apos;U&apos;
        ///  
        ///open dropsql_cursor
        ///  
        ///fetch dropsql_cursor into @tname
        ///  
        ///while @@fetch_status=0   
        ///begin  
        ///
        ///	IF ident_current(@tname) IS NOT NULL BEGIN
        ///		SET @sql = &apos;SET IDENTITY_INSERT [&apos; + @tname + &apos;] OFF&apos;;
        ///		execute(@sql);
        ///	END
        ///  
        ///    fetch dropsql_cursor into @tname   
        ///  
        ///end  
        ///close dropsql_cursor
        ///deallocate dropsql_cursor
        ///
        ///GO
        ///--end        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string _4_0_0_0803 {
            get {
                return ResourceManager.GetString("_4_0_0_0803", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF NOT EXISTS(SELECT * FROM sysindexes WHERE [id]=object_id(&apos;bx_UserRoles&apos;) AND [name]=&apos;IX_bx_UserRoles_EndDate&apos;) BEGIN
        ///	CREATE NONCLUSTERED INDEX [IX_bx_UserRoles_EndDate] ON [bx_UserRoles] ([EndDate]);
        ///END
        ///
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM sysindexes WHERE [id]=object_id(&apos;bx_UserInfos&apos;) AND [name]=&apos;IX_bx_UserInfos_TotalFriends&apos;) BEGIN
        ///	CREATE INDEX [IX_bx_UserInfos_TotalFriends] ON [bx_UserInfos] ([TotalFriends]);
        ///END
        ///
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM sysindexes WHERE [id]=object_id(&apos;bx_UserInfo [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string _4_0_0_0824 {
            get {
                return ResourceManager.GetString("_4_0_0_0824", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  
        /// DECLARE @NewUserID int,@NewUsername nvarchar(50),@TotalUser int;
        /// 
        /// SELECT TOP 1 @NewUserID=UserID,@NewUsername=Username FROM [bx_Users] WHERE [IsActive] = 1 AND [UserID]&lt;&gt;0 ORDER BY [UserID] DESC;
        /// 
        /// SELECT @TotalUser=Count(*) FROM [bx_Users] WHERE [IsActive] = 1 AND [UserID]&lt;&gt;0;
        ///
        /// IF @NewUserID IS NOT NULL BEGIN
        ///     IF EXISTS(SELECT * FROM [bx_Vars])
        ///         UPDATE [bx_Vars] SET  NewUserID = @NewUserID, NewUsername = @NewUsername, TotalUsers = @TotalUser WHERE [ID]=(SELECT TOP 1 ID FROM [bx_ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string _4_0_0_0826 {
            get {
                return ResourceManager.GetString("_4_0_0_0826", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  --BEGIN DROP TRIGGERS
        ///
        ///BEGIN
        ///
        ///	DECLARE cs_trgs CURSOR FOR SELECT DISTINCT t.name table_name,trg.name trigger_name FROM sysobjects t INNER JOIN sysobjects trg ON trg.parent_obj=t.id WHERE t.type=&apos;U &apos; AND trg.type=&apos;TR&apos; FOR READ ONLY
        ///	DECLARE @t_name NVARCHAR(100)
        ///	DECLARE @trg_name NVARCHAR(100)
        ///
        ///	OPEN cs_trgs
        ///
        ///	FETCH NEXT FROM cs_trgs INTO @t_name,@trg_name
        ///	WHILE @@FETCH_STATUS = 0
        ///	BEGIN
        ///		IF @t_name LIKE &apos;Max_%&apos; OR @t_name LIKE &apos;bbsMax_%&apos; OR @t_name LIKE &apos;System_Max_%&apos; OR @t_name LIKE &apos;Syste [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string _4_0_0_0901 {
            get {
                return ResourceManager.GetString("_4_0_0_0901", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string _4_0_0_0902 {
            get {
                return ResourceManager.GetString("_4_0_0_0902", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string _4_0_0_0908 {
            get {
                return ResourceManager.GetString("_4_0_0_0908", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///---UPDATE bx_Users SET UsedDiskSpaceSize=TotalFileSize FROM (SELECT SUM(FileSize) AS TotalFileSize,UserID FROM bx_DiskFiles GROUP BY UserID) AS D WHERE bx_Users.UserID = D.UserID; 的本地化字符串。
        /// </summary>
        public static string _4_0_3_0914 {
            get {
                return ResourceManager.GetString("_4_0_3_0914", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///IF NOT EXISTS (SELECT [name] FROM syscolumns WHERE id = object_id(&apos;bx_Files&apos;) AND [name] = &apos;FileID&apos;) BEGIN
        ///	EXEC (&apos;ALTER TABLE bx_Files ADD [FileID] varchar(50) COLLATE Chinese_PRC_CI_AS_WS NOT NULL DEFAULT(&apos;&apos;&apos;&apos;)&apos;);
        ///
        ///	EXEC (&apos;UPDATE bx_Files SET FileID = MD5 + CAST(FileSize as varchar(30))&apos;);
        ///
        ///END
        ///
        ///GO
        ///
        ///--处理照片----------------------------------------------------------------------
        ///
        ///--删除Photos表的FileID索引
        ///IF EXISTS (SELECT * FROM sysindexes WHERE name=&apos;IX_bx_Photos_FileID&apos;)
        ///	DROP INDEX bx_Photos.IX_ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string _4_1_0_1116 {
            get {
                return ResourceManager.GetString("_4_1_0_1116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF NOT EXISTS(SELECT * FROM syscolumns WHERE [id] =object_id(&apos;bx_UserInfos&apos;) AND [name] =&apos;UnreadPropNotifies&apos;)
        ///	EXEC (&apos;ALTER TABLE [bx_UserInfos] ADD [UnreadPropNotifies] [int] NOT NULL DEFAULT (0)&apos;);
        ///
        ///
        ///IF EXISTS(SELECT * FROM sysobjects WHERE [type]=N&apos;TR&apos; AND [name]=N&apos;bx_UserInfos_AfterUpdate&apos;)
        ///	EXEC (&apos;ALTER TABLE bx_UserInfos DISABLE TRIGGER bx_UserInfos_AfterUpdate&apos;);
        ///
        ///EXEC (&apos;
        ///Update bx_UserInfos SET
        ///  UnreadPropNotifies = 0 --道具
        /// ,UnreadSystemNotifies = 0 --管理
        ///  ,UnreadBidUpNotifies =0 --竞价排名 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string _4_1_0_1218 {
            get {
                return ResourceManager.GetString("_4_1_0_1218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF NOT EXISTS(SELECT * FROM syscolumns WHERE [id] =object_id(&apos;bx_UserInfos&apos;) AND [name] =&apos;UnreadPropNotifies&apos;)
        ///	EXEC (&apos;ALTER TABLE [bx_UserInfos] ADD [UnreadPropNotifies] [int] NOT NULL DEFAULT (0)&apos;);
        ///
        ///
        ///IF EXISTS(SELECT * FROM sysobjects WHERE [type]=N&apos;TR&apos; AND [name]=N&apos;bx_UserInfos_AfterUpdate&apos;)
        ///	EXEC (&apos;ALTER TABLE bx_UserInfos DISABLE TRIGGER bx_UserInfos_AfterUpdate&apos;);
        ///
        ///EXEC (&apos;
        ///Update bx_UserInfos SET
        ///  UnreadPropNotifies = 0 --道具
        /// ,UnreadSystemNotifies = 0 --管理
        ///  ,UnreadBidUpNotifies =0 --竞价排名 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string _4_2_0_1218 {
            get {
                return ResourceManager.GetString("_4_2_0_1218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///IF NOT EXISTS (SELECT * FROM sysobjects WHERE [name]=&apos;bx_Serials&apos; AND type=&apos;U&apos;) BEGIN
        ///
        ///	CREATE TABLE [bx_Serials] (
        ///	   [Serial]           uniqueidentifier                                 NOT NULL    CONSTRAINT [DF_bx_bx_Serials_Serial]          DEFAULT (NEWID())
        ///	  
        ///	  ,[UserID]           int                                              NOT NULL
        ///	  
        ///	  ,[CreateDate]       datetime                                         NOT NULL    CONSTRAINT [DF_bx_bx_Serials_CreateDate]      DEFAULT (GETDATE())        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string _4_2_2_0130 {
            get {
                return ResourceManager.GetString("_4_2_2_0130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF NOT EXISTS(SELECT * FROM syscolumns WHERE [id] =object_id(&apos;bx_PointShows&apos;) AND [name] =&apos;Price&apos;) BEGIN
        ///	EXEC (&apos; ALTER TABLE [bx_PointShows] ADD [Price] [int] NOT NULL DEFAULT (0)&apos;);
        ///	EXEC (&apos; UPDATE [bx_PointShows] SET [Price] = 1; &apos;);
        ///END
        ///
        ///IF NOT EXISTS(SELECT * FROM syscolumns WHERE [id] =object_id(&apos;bx_PostMarks&apos;) AND [name] =&apos;Username&apos;) BEGIN
        ///	EXEC (&apos; ALTER TABLE [bx_PostMarks] ADD [Username] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS_WS NOT NULL  DEFAULT (&apos;&apos;&apos;&apos;) &apos;);
        ///	EXEC (&apos; UPDATE [bx_PostMarks]  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string _5_0_0_0331 {
            get {
                return ResourceManager.GetString("_5_0_0_0331", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DELETE bx_Polemizes WHERE ThreadID NOT IN(SELECT ThreadID FROM bx_Threads) 的本地化字符串。
        /// </summary>
        public static string _5_0_0_0926 {
            get {
                return ResourceManager.GetString("_5_0_0_0926", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap alert {
            get {
                object obj = ResourceManager.GetObject("alert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///
        ///  &lt;connectionStrings&gt;
        ///    &lt;add connectionString=&quot;$(connectionString)&quot; name=&quot;bbsmax&quot; providerName=&quot;MaxLabs.bbsMax.DataAccess.SqlServer.DataProvider, MaxLabs.bbsMax.DataAccess.SqlServer&quot; /&gt;
        ///  &lt;/connectionStrings&gt;
        ///
        ///  &lt;appSettings&gt;
        ///    &lt;add key=&quot;bbsMax.InstallPath&quot; value=&quot;~/&quot;/&gt;
        ///    &lt;add key=&quot;bbsMax.DynamicCompress&quot; value=&quot;$(DynamicCompress)&quot; /&gt;
        ///    &lt;!-- 是否启用动态内容压缩，如果启用后出错请把value改为OFF --&gt;
        ///    &lt;add key=&quot;bbsMax.StaticCompress&quot; value=&quot;$(StaticCompre [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string bbsmax_config {
            get {
                return ResourceManager.GetString("bbsmax_config", resourceCulture);
            }
        }
        
        public static byte[] bbsmax_zip {
            get {
                object obj = ResourceManager.GetObject("bbsmax_zip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static System.Drawing.Bitmap checkconnect {
            get {
                object obj = ResourceManager.GetObject("checkconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 --BEGIN DROP FKS
        ///--DECLARE @IsSQL2000 bit;
        ///--IF CHARINDEX(&apos;Microsoft SQL Server  2000&apos;, @@VERSION) = 1
        ///	--SET @IsSQL2000 = 1;
        ///--ELSE
        ///	--SET @IsSQL2000 = 0;
        ///	
        ///BEGIN
        ///	DECLARE @username NVARCHAR(256)
        ///	DECLARE @t_name NVARCHAR(100)
        ///	DECLARE @fk_name NVARCHAR(100)
        ///	
        ///		DECLARE cs_fks CURSOR FOR SELECT schema_name(ot.schema_id),ot.name out_table_name,object_name(fk.constid) constraint_name FROM sysforeignkeys fk INNER JOIN sys.objects ot ON ot.object_id=fk.fkeyid ORDER BY ot.object_id,fk.constid FOR RE [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string clean_all {
            get {
                return ResourceManager.GetString("clean_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///BEGIN
        ///	DECLARE @username NVARCHAR(256)
        ///	DECLARE @t_name NVARCHAR(100)
        ///	DECLARE @fk_name NVARCHAR(100)
        ///		DECLARE cs_fks CURSOR FOR SELECT user_name(ot.uid),ot.name out_table_name,object_name(fk.constid) constraint_name FROM sysforeignkeys fk INNER JOIN sysobjects ot ON ot.id=fk.fkeyid ORDER BY ot.id,fk.constid FOR READ ONLY
        ///
        ///
        ///		OPEN cs_fks
        ///
        ///		FETCH NEXT FROM cs_fks INTO @username,@t_name,@fk_name
        ///		WHILE @@FETCH_STATUS = 0
        ///		BEGIN
        ///			IF @username IS NOT NULL BEGIN
        ///				IF @t_name LIKE &apos;Max_%&apos; O [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string clean_all_2000 {
            get {
                return ResourceManager.GetString("clean_all_2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///--BEGIN DROP TRIGGERS
        ///	
        ///BEGIN
        ///	DECLARE @username NVARCHAR(256)
        ///	DECLARE @t_name NVARCHAR(100)
        ///	DECLARE @trg_name NVARCHAR(100)
        ///		DECLARE cs_trgs CURSOR FOR SELECT DISTINCT schema_name(t.schema_id),t.name table_name,trg.name trigger_name FROM sys.objects t INNER JOIN sys.objects trg ON trg.parent_object_id=t.object_id WHERE t.type=&apos;U&apos; AND trg.type=&apos;TR&apos; FOR READ ONLY
        ///
        ///		OPEN cs_trgs
        ///
        ///		FETCH NEXT FROM cs_trgs INTO @username,@t_name,@trg_name
        ///		WHILE @@FETCH_STATUS = 0
        ///		BEGIN
        ///			IF @username  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string clean_upgrade {
            get {
                return ResourceManager.GetString("clean_upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///--BEGIN DROP TRIGGERS
        ///	
        ///BEGIN
        ///	DECLARE @username NVARCHAR(256)
        ///	DECLARE @t_name NVARCHAR(100)
        ///	DECLARE @trg_name NVARCHAR(100)
        ///		DECLARE cs_trgs CURSOR FOR SELECT DISTINCT user_name(t.uid),t.name table_name,trg.name trigger_name FROM sysobjects t INNER JOIN sysobjects trg ON trg.parent_obj=t.id WHERE t.type=&apos;U&apos; AND trg.type=&apos;TR&apos; FOR READ ONLY
        ///
        ///
        ///		OPEN cs_trgs
        ///
        ///		FETCH NEXT FROM cs_trgs INTO @username,@t_name,@trg_name
        ///		WHILE @@FETCH_STATUS = 0
        ///		BEGIN
        ///			IF @username IS NOT NULL BEGIN
        ///		 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string clean_upgrade_2000 {
            get {
                return ResourceManager.GetString("clean_upgrade_2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF EXISTS (SELECT [name] FROM sysobjects WHERE [name]=&apos;bx_Drop&apos; AND [type]=&apos;P&apos;)
        ///   DROP PROCEDURE bx_Drop
        ///GO
        ///
        ///CREATE PROCEDURE bx_Drop @Name sysname
        ///AS
        ///BEGIN
        ///
        ///	IF OBJECT_ID(@Name) IS NULL
        ///		RETURN;
        ///
        ///
        ///	/* 删除指定名称的表 */
        ///	IF EXISTS (SELECT * FROM [sysobjects] WHERE [type] = &apos;U&apos; AND [name] = @Name) BEGIN
        ///		
        ///		DECLARE cs_trgs CURSOR FOR SELECT [name] FROM [sysobjects] WHERE [type] = &apos;F&apos; and parent_obj = OBJECT_ID(@Name) FOR READ ONLY
        ///		DECLARE @t_name NVARCHAR(100)
        ///
        ///		OPEN cs_trgs
        ///
        ///		FETCH NEXT [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _codes\announcements.aspx.cs
        ///_codes\bindemail.aspx.cs
        ///_codes\emailvalidator.aspx.cs
        ///_codes\login.aspx.cs
        ///_codes\loginemailbind.aspx.cs
        ///_codes\logout.aspx.cs
        ///_codes\members.aspx.cs
        ///_codes\recoverpassword.aspx.cs
        ///_codes\register.aspx.cs
        ///_codes\search.aspx.cs
        ///_codes\_master_page_.aspx.cs
        ///_codes\_master_window_.aspx.cs
        ///_codes\_part\post_success.aspx.cs
        ///_codes\_part\toolbar_friend.aspx.cs
        ///_codes\_part\toolbar_message.aspx.cs
        ///_codes\_part\toolbar_notify.aspx.cs
        ///_codes\_part\toolbar_report.aspx.cs        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string filelist {
            get {
                return ResourceManager.GetString("filelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --忽略错误 修改 所有对象的所有者为当前登陆用户 
        ///declare @s nvarchar(4000)
        ///declare tb cursor local for
        ///select &apos;sp_changeobjectowner &apos;&apos;[&apos;+replace(schema_name(schema_id),&apos;]&apos;,&apos;]]&apos;)+&apos;].[&apos;+replace(name,&apos;]&apos;,&apos;]]&apos;)+&apos;]&apos;&apos;,&apos;&apos;&apos;+schema_name()+&apos;&apos;&apos;&apos;
        ///from sys.objects
        ///where type in(&apos;U&apos;,&apos;V&apos;,&apos;P&apos;,&apos;FN&apos;,&apos;IF&apos;,&apos;TF&apos;) and schema_name(schema_id)&lt;&gt;schema_name()
        ///and (name LIKE &apos;Max_%&apos; OR name LIKE &apos;bbsMax_%&apos; OR name LIKE &apos;System_Max_%&apos; OR name LIKE &apos;System_bbsMax_%&apos; OR name LIKE &apos;bx_%&apos;)
        ///open tb
        ///fetch tb into @s
        ///while @@fetch_status=0
        ///begin
        ///exec(@ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string first {
            get {
                return ResourceManager.GetString("first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --忽略错误 修改 所有对象的所有者为当前登陆用户 
        ///declare @s nvarchar(4000)
        ///declare tb cursor local for
        ///select &apos;sp_changeobjectowner &apos;&apos;[&apos;+replace(user_name(uid),&apos;]&apos;,&apos;]]&apos;)+&apos;].[&apos;+replace(name,&apos;]&apos;,&apos;]]&apos;)+&apos;]&apos;&apos;,&apos;&apos;&apos;+user_name()+&apos;&apos;&apos;&apos;
        ///from sysobjects
        ///where xtype in(&apos;U&apos;,&apos;V&apos;,&apos;P&apos;,&apos;FN&apos;,&apos;IF&apos;,&apos;TF&apos;) and status&gt;=0 and user_name(uid)&lt;&gt;user_name()
        ///and (name LIKE &apos;Max_%&apos; OR name LIKE &apos;bbsMax_%&apos; OR name LIKE &apos;System_Max_%&apos; OR name LIKE &apos;System_bbsMax_%&apos; OR name LIKE &apos;bx_%&apos;)
        ///open tb
        ///fetch tb into @s
        ///while @@fetch_status=0
        ///begin
        ///exec(@s)
        ///fe [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string first_2000 {
            get {
                return ResourceManager.GetString("first_2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;%@ Application Language=&quot;C#&quot; Inherits=&quot;MaxLabs.bbsMax.Web._Global&quot; %&gt; 的本地化字符串。
        /// </summary>
        public static string Global_asax {
            get {
                return ResourceManager.GetString("Global_asax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///-- 插入系统需要的一个默认用户 --
        ///IF NOT EXISTS (SELECT * FROM bx_Users WHERE UserID = 0) BEGIN
        ///
        ///	SET IDENTITY_INSERT [bx_Users] ON;
        ///
        ///	INSERT INTO [bx_Users] ([UserID], [Username]) VALUES(0, &apos;{#bxguest#}&apos;);
        ///
        ///	SET IDENTITY_INSERT [bx_Users] OFF;
        ///
        ///END
        ///
        ///ELSE IF NOT EXISTS (SELECT * FROM bx_Users WHERE UserID = 0 AND Username = &apos;{#bxguest#}&apos;)
        ///	UPDATE bx_Users SET Username = &apos;{#bxguest#}&apos; WHERE UserID = 0;
        ///
        ///GO
        ///
        ///-- 插入系统需要的两个默认好友分组 --
        ///IF NOT EXISTS (SELECT * FROM [bx_FriendGroups] WHERE GroupID = -1) BEGIN
        ///        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string lastsql {
            get {
                return ResourceManager.GetString("lastsql", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap loader {
            get {
                object obj = ResourceManager.GetObject("loader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 body, ul, p, h1, h2, h3 {
        ///    margin: 0;
        ///    padding: 0;
        ///    list-style: none;
        ///    color: #222;
        ///    font: 100%/1.5 &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif;
        ///}
        ///a:link, a:visited {
        ///    color: #06c;
        ///    text-decoration: none;
        ///}
        ///input {
        ///    font-family: inherit;
        ///}
        ///body {
        ///    text-align: center;
        ///}
        ///.container {
        ///    width: 750px;
        ///    text-align: left; 
        ///    margin: 40px auto 0;
        ///    border: 1px solid #cde;
        ///    background: #e3f3ff;
        ///    font-size: 75%;
        ///}
        ///.footer {
        ///    width: 750px;
        ///    margi [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string max_install_css {
            get {
                return ResourceManager.GetString("max_install_css", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap maxInstall {
            get {
                object obj = ResourceManager.GetObject("maxInstall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap no {
            get {
                object obj = ResourceManager.GetObject("no", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ok {
            get {
                object obj = ResourceManager.GetObject("ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DbDatabase xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Edition&gt;Unknown&lt;/Edition&gt;
        ///  &lt;PrimaryObjectInfos /&gt;
        ///  &lt;OutObjectInfos /&gt;
        ///  &lt;UserTypes&gt;
        ///    &lt;Instance&gt;
        ///      &lt;item&gt;
        ///        &lt;key&gt;
        ///          &lt;int&gt;34&lt;/int&gt;
        ///        &lt;/key&gt;
        ///        &lt;value&gt;
        ///          &lt;DbUserType UserTypeId=&quot;34&quot; Name=&quot;image&quot; MaxLength=&quot;16&quot; Precision=&quot;0&quot; Scale=&quot;0&quot; /&gt;
        ///        &lt;/value&gt;
        ///      &lt;/item&gt;
        ///      &lt;item&gt;
        ///        &lt;key&gt;
        ///        [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string scheme_xml {
            get {
                return ResourceManager.GetString("scheme_xml", resourceCulture);
            }
        }
    }
}