var editorMode={html:"html",ubb:"ubb"},KE={};
KE.lang={source:"\u5207\u6362\u6a21\u5f0f",preview:"\u9884\u89c8",zoom:"\u653e\u5927",undo:"\u540e\u9000",redo:"\u524d\u8fdb",cut:"\u526a\u5207",copy:"\u590d\u5236",paste:"\u7c98\u8d34",plainpaste:"\u7c98\u8d34\u4e3a\u65e0\u683c\u5f0f\u6587\u672c",wordpaste:"\u4eceWord\u7c98\u8d34",selectall:"\u5168\u9009",justifyleft:"\u5de6\u5bf9\u9f50",justifycenter:"\u5c45\u4e2d",justifyright:"\u53f3\u5bf9\u9f50",justifyfull:"\u4e24\u7aef\u5bf9\u9f50",insertorderedlist:"\u7f16\u53f7",insertunorderedlist:"\u9879\u76ee\u7b26\u53f7",
indent:"\u589e\u52a0\u7f29\u8fdb",outdent:"\u51cf\u5c11\u7f29\u8fdb",subscript:"\u4e0b\u6807",superscript:"\u4e0a\u6807",date:"\u63d2\u5165\u5f53\u524d\u65e5\u671f",time:"\u63d2\u5165\u5f53\u524d\u65f6\u95f4",fontname:"\u5b57\u4f53",fontsize:"\u6587\u5b57\u5927\u5c0f",textcolor:"\u6587\u5b57\u989c\u8272",bgcolor:"\u6587\u5b57\u80cc\u666f",bold:"\u7c97\u4f53",italic:"\u659c\u4f53",underline:"\u4e0b\u5212\u7ebf",strikethrough:"\u5220\u9664\u7ebf",removeformat:"\u5220\u9664\u683c\u5f0f",image:"\u63d2\u5165\u56fe\u7247",
flash:"\u63d2\u5165Flash",media:"\u63d2\u5165\u591a\u5a92\u4f53",audio:"\u97f3\u9891",video:"\u89c6\u9891",layer:"\u63d2\u5165\u5c42",table:"\u63d2\u5165\u8868\u683c",emoticons:"\u8868\u60c5",photo:"\u56fe\u7247",attachment:"\u9644\u4ef6",link:"\u8d85\u7ea7\u8fde\u63a5",unlink:"\u53d6\u6d88\u8d85\u7ea7\u8fde\u63a5",code:"\u63d2\u5165\u4ee3\u7801",hide:"\u63d2\u5165\u9690\u85cf\u5185\u5bb9",fullscreen:"\u5168\u5c4f\u663e\u793a",yes:"\u786e\u5b9a",no:"\u53d6\u6d88",close:"\u5173\u95ed",quote:"\u63d2\u5165\u5f15\u7528",
free:"\u63d2\u5165\u514d\u8d39\u5185\u5bb9",fontTable:{SimSun:"\u5b8b\u4f53",SimHei:"\u9ed1\u4f53",FangSong_GB2312:"\u4eff\u5b8b\u4f53",KaiTi_GB2312:"\u6977\u4f53",NSimSun:"\u65b0\u5b8b\u4f53",Arial:"Arial","Arial Black":"Arial Black","Times New Roman":"Times New Roman","Courier New":"Courier New",Tahoma:"Tahoma",Verdana:"Verdana"},colorTable:[["#FFFFFF","#E5E4E4","#D9D8D8","#C0BDBD","#A7A4A4","#8E8A8B","#827E7F","#767173","#5C585A","#000000"],["#FEFCDF","#FEF4C4","#FEED9B","#FEE573","#FFED43","#F6CC0B",
"#E0B800","#C9A601","#AD8E00","#8C7301"],["#FFDED3","#FFC4B0","#FF9D7D","#FF7A4E","#FF6600","#E95D00","#D15502","#BA4B01","#A44201","#8D3901"],["#FFD2D0","#FFBAB7","#FE9A95","#FF7A73","#FF483F","#FE2419","#F10B00","#D40A00","#940000","#6D201B"],["#FFDAED","#FFB7DC","#FFA1D1","#FF84C3","#FF57AC","#FD1289","#EC0078","#D6006D","#BB005F","#9B014F"],["#FCD6FE","#FBBCFF","#F9A1FE","#F784FE","#F564FE","#F546FF","#F328FF","#D801E5","#C001CB","#8F0197"],["#E2F0FE","#C7E2FE","#ADD5FE","#92C7FE","#6EB5FF","#48A2FF",
"#2690FE","#0162F4","#013ADD","#0021B0"],["#D3FDFF","#ACFAFD","#7CFAFF","#4AF7FE","#1DE6FE","#01DEFF","#00CDEC","#01B6DE","#00A0C2","#0084A0"],["#EDFFCF","#DFFEAA","#D1FD88","#BEFA5A","#A8F32A","#8FD80A","#79C101","#3FA701","#307F00","#156200"],["#D4C89F","#DAAD88","#C49578","#C2877E","#AC8295","#C0A5C4","#969AC2","#92B7D7","#80ADAF","#9CA53B"]],invalidSwf:"\u8bf7\u8f93\u5165\u6709\u6548\u7684URL\u5730\u5740\u3002\n\u53ea\u5141\u8bb8swf,flv\u683c\u5f0f\u3002",invalidImg:"\u8bf7\u8f93\u5165\u6709\u6548\u7684URL\u5730\u5740\u3002\n\u53ea\u5141\u8bb8jpg,gif,bmp,png\u683c\u5f0f\u3002",
invalidMedia:"\u8bf7\u8f93\u5165\u6709\u6548\u7684URL\u5730\u5740\u3002\n\u53ea\u5141\u8bb8mp3,wav,wma,wmv,mid,avi,mpg,asf,rm,rmvb,swf,flv\u683c\u5f0f\u3002",invalidWidth:"\u5bbd\u5ea6\u5fc5\u987b\u4e3a\u6570\u5b57\u3002",invalidHeight:"\u9ad8\u5ea6\u5fc5\u987b\u4e3a\u6570\u5b57\u3002",invalidBorder:"\u8fb9\u6846\u5fc5\u987b\u4e3a\u6570\u5b57\u3002",invalidUrl:"URL\u4e0d\u6b63\u786e\u3002",pleaseInput:"\u8bf7\u8f93\u5165\u5185\u5bb9",shrink:"\u51cf\u5c11\u9ad8\u5ea6",elongate:"\u589e\u52a0\u9ad8\u5ea6"};
KE.$=function(a,b){b=b||document;return b.getElementById(a)};KE.$$=function(a,b){b=b||document;return b.createElement(a)};KE.event={add:function(a,b,c){if(a.addEventListener)a.addEventListener(b,c,false);else a.attachEvent&&a.attachEvent("on"+b,c)},remove:function(a,b,c){if(a.removeEventListener)a.removeEventListener(b,c,false);else a.detachEvent&&a.detachEvent("on"+b,c)}};KE.each=function(a,b){for(var c in a)a.hasOwnProperty(c)&&b(c,a[c])};
KE.util={getDocumentElement:function(){return document.compatMode!="CSS1Compat"?document.body:document.documentElement},getDocumentHeight:function(){var a=this.getDocumentElement();return Math.max(a.scrollHeight,a.clientHeight)},getDocumentWidth:function(){var a=this.getDocumentElement();return Math.max(a.scrollWidth,a.clientWidth)},getScriptPath:function(){for(var a=document.getElementsByTagName("script"),b=0;b<a.length;b++)if(a[b].src&&a[b].src.match(/kindeditor[\w\-\.]*\.js/)!=null)return a[b].src.substring(0,
a[b].src.lastIndexOf("/")+1)},getHtmlPath:function(){return location.href.substring(0,location.href.lastIndexOf("/")+1)},getBrowser:function(){var a=navigator.userAgent.toLowerCase(),b={};b.IsIE=a.indexOf("msie")>-1;b.IsIE6=a.indexOf("msie 6")>-1;b.IsIE7=a.indexOf("msie 7")>-1;b.IsFF=a.indexOf("firefox")>-1;b.IsOpera=a.indexOf("opera")>-1;b.IsGecko=a.indexOf("gecko")>-1;b.IsSafari=a.indexOf("safari")>-1;b.IsChrome=a.indexOf("chrome")>-1;return b},loadStyle:function(a){var b=KE.$$("link");b.setAttribute("type",
"text/css");b.setAttribute("rel","stylesheet");b.setAttribute("href",a);document.getElementsByTagName("head")[0].appendChild(b)},inArray:function(a,b){for(var c=0;c<b.length;c++)if(a==b[c])return true;return false},escape:function(a){a=a.replace(/&/g,"&amp;");a=a.replace(/</g,"&lt;");a=a.replace(/>/g,"&gt;");a=a.replace(/\xA0/g,"&nbsp;");return a=a.replace(/\x20/g," ")},createLink:function(a,b){KE.util.select(a);var c=KE.g[a].iframeDoc,d=KE.g[a].range;b=b;if(b.match(/\w+:\/\/.{3,}/)==null){alert(KE.lang.invalidUrl);
window.focus();return false}var e;if(KE.browser.IsIE){if(d.item)e=d.item(0).parentNode}else if(d.startContainer==d.endContainer)e=d.startContainer.parentNode;var f='<a href="'+b+'" target="_blank">'+b+"</a>",g="[url="+b+"]"+b+"[/url]",h=false;if(h=d.collapsed||KE.browser.IsIE&&!d.htmlText)KE.util.insertContent(a,f,g);else{if(e&&e.tagName=="A")e=e.parentNode;if(!e)e=c.body;c.execCommand("createlink",false,"__ke_temp_url__");c=e.getElementsByTagName("a");d=0;for(e=c.length;d<e;d++)if(c[d].href.match(/\/?__ke_temp_url__$/)!=
null){c[d].href=b;c[d].target="_blank"}KE.history.add(a);KE.layout.hide(a);KE.util.focus(a)}},getElementPos:function(a){var b=0,c=0;if(a.getBoundingClientRect){c=a.getBoundingClientRect();a=this.getDocumentElement();b=c.left+a.scrollLeft-a.clientLeft;c=c.top+a.scrollTop-a.clientTop}else{b=a.offsetLeft;c=a.offsetTop;for(a=a.offsetParent;a;){b+=a.offsetLeft;c+=a.offsetTop;a=a.offsetParent}}return{x:b,y:c}},getCoords:function(a){a=a||window.event;var b=this.getDocumentElement();if(a.pageX)return{x:a.pageX,
y:a.pageY};return{x:a.clientX+b.scrollLeft-b.clientLeft,y:a.clientY+b.scrollTop-b.clientTop}},setOpacity:function(a,b){if(KE.browser.IsIE)a.style.filter=b==100?"":"gray() alpha(opacity="+b+")";else a.style.opacity=b==100?"":"0."+b.toString()},showBottom:function(){},hideBottom:function(){},drag:function(a,b,c,d){var e=KE.g[a];b.onmousedown=function(f){KE.browser.IsIE||f.preventDefault();f=KE.util.getCoords(f||window.event);var g=parseInt(c.style.top),h=parseInt(c.style.left),i=parseInt(c.style.width),
k=parseInt(c.style.height),m=f.y,p=f.x,l=true,o=function(x){if(l){x=KE.util.getCoords(x||window.event);d(g,h,i,k,x.y-m,x.x-p)}return false},t=function(){if(e.wyswygMode)e.iframe.style.display="";l=false;KE.event.remove(document,"mousemove",o);KE.event.remove(document,"mouseup",t)};KE.event.add(document,"mousemove",o);KE.event.add(document,"mouseup",t)}},setDefaultPlugin:function(){for(var a=["cut","copy","paste","selectall","justifyfull","outdent","removeformat","unlink"],b=0;b<a.length;b++)KE.plugin[a[b]]=
{click:new Function("id",'KE.util.execCommand(id, "'+a[b]+'", null);')};a=[["justifyleft","align=left"],["justifycenter","align=center"],["justifyright","align=right"],["indent","indent"],["subscript","sub"],["superscript","sup"],["bold","b"],["italic","i"],["underline","u"],["strikethrough","s"],["free","free"],["quote","quote"]];for(b=0;b<a.length;b++)KE.plugin[a[b][0]]={click:new Function("id",'KE.util.execCommand(id, "'+a[b][0]+'", null);'),ubbClick:new Function("id",'KE.util.execUbb(id, "'+a[b][1]+
'", null);')};a=[["flash",-1,-1],["photo",-1,-1],["audio",-1,-1],["video",-1,-1],["attachment",-1,-1],["code",350,290],["wordpaste",350,310],["hide",350,310],["plainpaste",350,310],["link",300,130]];for(b=0;b<a.length;b++)KE.plugin[a[b][0]]={click:new Function("id",'KE.panel.show(id, "'+a[b][0]+'", '+a[b][1]+", "+a[b][2]+");"),ubbClick:function(c){this.click(c)}};KE.activable=["justifyleft","justifycenter","justifyright","justifyfull","insertorderedlist","insertunorderedlist","indent","outdent","subscript",
"superscript","bold","italic","underline","strikethrough","removeformat","unlink"]},getIframeDoc:function(a){var b=null;return b=a.contentDocument?a.contentDocument:a.contentWindow.document},getFullHtml:function(a){var b="<html>";b+="<head>";b+='<base href="'+KE.htmlPath+'" />';b+="<title>editor</title>";if(KE.g[a].cssPath)b+='<link href="'+KE.g[a].cssPath+'" rel="stylesheet" type="text/css" />';b+="</head>";b+="<body>";b+="</body>";b+="</html>";return b},resize:function(a,b,c){a=KE.g[a];if(!(c<=
a.minHeight)){var d=a.toolbarDiv,e=a.container.style;c=c;c-=a.bottomDiv.offsetHeight;c-=d.offsetHeight;c-=10;e.width=b.toString().indexOf("%")>-1?b:b+"px";e=a.formDiv.style;e.height=c+"px";if(KE.browser.IsIE6||KE.browser.IsIE7)a.newTextarea.style.height=c+"px"}},shrink:function(a){var b=KE.g[a];if(!b.fullscreenMode){b.minHeight=b.minHeight||120;var c=b.container.offsetHeight;if(!(c<=100||c<=b.minHeight)){var d=-80;c+=d;if(c<b.minHeight)d+=b.minHeight-c;c=b.formDiv;c.style.height=(b.wyswygMode?b.iframe.offsetHeight+
d:b.newTextarea.offsetHeight+d)+"px";if(KE.browser.IsIE6||KE.browser.IsIE7)KE.$("ke_textarea_"+a).style.height=c.style.height}}},elongate:function(a){var b=KE.g[a];if(!b.fullscreenMode){parseInt(b.height);var c=b.formDiv;c.style.height=(b.wyswygMode?b.iframe.offsetHeight+80:b.newTextarea.offsetHeight+80)+"px";if(KE.browser.IsIE6||KE.browser.IsIE7)KE.$("ke_textarea_"+a).style.height=c.style.height}},setValue:function(a,b,c){KE.util.getCurrentMode(a);if(KE.g[a].wyswygMode){if(c=="ubb")b=ubb2html(b);
KE.util.getIframeDoc(KE.g[a].iframe).body.innerHTML=b}else KE.g[a].newTextarea.value=b},getData:function(a,b){var c=false;c=KE.util.getCurrentMode(a)=="ubb";b=typeof b=="undefined"?true:b;if(KE.g[a].wyswygMode){a=b?KE.util.outputHtml(a,KE.g[a].iframeDoc.body):KE.g[a].iframeDoc.body.innerHTML;if(c)a=html2ubb(a);else{if(window.beforeProcessImg)a=window.beforeProcessImg(a);a=KE.util.flag2Html(a)}}else a=KE.g[a].newTextarea.value;return a},setData:function(a){var b=this.getData(a,KE.g[a].filterMode);
KE.g[a].srcTextarea.value=b},focus:function(a){KE.g[a].wyswygMode?KE.g[a].iframeWin.focus():KE.g[a].newTextarea.focus()},click:function(a,b){KE.layout.hide(a);KE.util.focus(a);if(KE.g[a].wyswygMode){KE.plugin[b].click(a);KE.util.setActived(a)}else KE.plugin[b].ubbClick&&KE.plugin[b].ubbClick(a)},selection:function(a){var b=KE.g[a].iframeWin,c=KE.g[a].iframeDoc;b.focus();b=b.getSelection?b.getSelection():c.selection;var d;try{d=b.rangeCount>0?b.getRangeAt(0):b.createRange?b.createRange():c.createRange()}catch(e){}d||
(d=KE.browser.IsIE?c.body.createTextRange():c.createRange());KE.g[a].selection=b;KE.g[a].range=d},select:function(a){var b=KE.g[a].range;if(KE.browser.IsIE)b&&b.select();else KE.util.selection(a)},pToBr:function(a){KE.browser.IsIE&&KE.event.add(KE.g[a].iframeDoc,"keypress",function(b){if(b.keyCode==13&&b.ctrlKey==false){KE.util.selection(a);if(KE.g[a].range.parentElement().tagName!="LI"){KE.util.insertHtml(a,"<br />");KE.util.select(a);return b.returnValue=false}}})},createBlock:function(a,b,c){var d=
KE.g[a].iframeDoc;KE.util.selection(a);if(KE.browser.IsIE){var e=d.selection.createRange();e.pasteHTML(b+e.htmlText+c)}else{e=KE.g[a].range;var f=e.extractContents();e=KE.g[a].range;e.collapse(true);b=d.createTextNode(b);c=d.createTextNode(c);f.insertBefore(b,f.childNodes[0]);f.appendChild(c);e.insertNode(f);e.setEndBefore(c);e.collapse(false)}},execCommand:function(a,b,c){if(b=="free"||b=="quote")this.createBlock(a,"["+b+"]","[/"+b+"]");else{try{KE.g[a].iframeDoc.execCommand(b,false,c)}catch(d){}KE.history.add(a,
false)}},callCtrlEnter:function(a,b){b=window.event||b;if(b.ctrlKey&&b.keyCode==13){var c=KE.g[a].onCtrlEnter;if(c){KE.util.setData(a);c();return b.returnValue=false}}},execUbb:function(a,b){var c=b;a=KE.g[a].newTextarea;if(c.indexOf("=")!=-1)c=c.substring(0,c.indexOf("="));a.focus();if(document.selection){a=document.selection.createRange();a.text="["+b+"]"+a.text+"[/"+c+"]"}else{var d=a.value,e=a.selectionStart;sl=a.selectionEnd-a.selectionStart;ts="["+b+"]";te="[/"+c+"]";d=d.substring(0,e)+ts+d.substring(e);
e+=ts.length+sl;d=d.substring(0,e)+te+d.substring(e);a.value=d}},setActived:function(a){for(var b=0;b<KE.activable.length;b++){var c=KE.activable[b],d=KE.g[a].toolbarIcon[c];if(d)if(KE.g[a].wyswygMode)KE.util.queryCommandState(a,c)?KE.util.addClassName(d,"selected"):KE.util.removeClassName(d,"selected")}},queryCommandState:function(a,b){try{return KE.g[a].iframeDoc.queryCommandState(b)?true:false}catch(c){return false}},setWyswygMode:function(a){var b=KE.util.getCurrentMode(a),c=KE.g[a];if(!c.wyswygMode){var d=
c.newTextarea.value;if(b=="ubb")d=ubb2html(d);else{d=KE.util.html2Flag(d);if(window.beforeProcessUbbImg)d=window.beforeProcessUbbImg(d)}c.iframeDoc.body.innerHTML=d;c.iframe.style.display="block";c.newTextarea.style.display="none";c.tabDiv.tabItem_1.className="current";c.tabDiv.tabItem_2.className="";c.wyswygMode=true;KE.util.focus(a)}},setSourceMode:function(a){var b=KE.g[a];if(b.wyswygMode!=false){KE.layout.hide(a);var c=KE.util.getCurrentMode(a),d;d=KE.g[a].filterMode?KE.util.outputHtml(a,b.iframeDoc.body):
b.iframeDoc.body.innerHTML;if(c=="ubb")d=html2ubb(d);else{d=KE.util.flag2Html(d);if(window.beforeProcessImg)d=window.beforeProcessImg(d)}b.newTextarea.value=d;b.tabDiv.tabItem_1.className="";b.tabDiv.tabItem_2.className="current";b.iframe.style.display="none";b.newTextarea.style.display="block";b.wyswygMode=false;KE.util.focus(a)}},insertContent:function(a,b,c){KE.util.focus(a);var d=KE.util.getCurrentMode(a),e=KE.g[a].wyswygMode||d=="html"?b:c;if(KE.g[a].wyswygMode)KE.util.insertHtml(a,b);else{if(d==
"ubb"&&!c)e=html2ubb(b);else if(d=="html")e=KE.util.flag2Html(b);KE.util.insertUbb(a,e)}},insertUbb:function(a,b){if(b){var c=KE.g[a].newTextarea;KE.util.select(a);c.focus();if(document.selection)document.selection.createRange().text=b;else{a=c.value;var d=c.value.length,e=c.selectionStart;c.value=a.substr(0,e)+b+a.substring(e,d);c.selectionStart=e+b.length;c.selectionEnd=e+b.length}}},createUbbTag:function(){},setCurrentMode:function(a,b){var c=KE.util.getCurrentMode(a);if(b!=c){c=KE.g[a];window.ke_EditorMode[a]=
b;if(c&&KE.g[a].isCreated)if(!c.wyswygMode){a=c.newTextarea.value;if(b=="html"){a=ubb2html(a);a=KE.util.flag2Html(a);if(window.beforeProcessImg)a=window.beforeProcessImg(a)}else if(b=="ubb")a=html2ubb(a);c.newTextarea.value=a}}},getCurrentMode:function(a){if(!window.ke_EditorMode)window.ke_EditorMode={};window.ke_EditorMode[a]||(window.ke_EditorMode[a]="html");return window.ke_EditorMode[a]},insertHtml:function(a,b){if(b!=""){KE.util.select(a);if(KE.browser.IsIE)if(!document.implementation.hasFeature("Range",
"2.0")){if(KE.g[a].selection.type.toLowerCase()=="control")KE.g[a].range.item(0).outerHTML=b;else KE.g[a].range.pasteHTML(b);KE.history.add(a,false);return}this.execCommand(a,"inserthtml",b)}},removeDomain:function(a,b){a=KE.g[a].siteDomains;for(var c=0,d=a.length;c<d;c++){var e="http://"+a[c];if(b.indexOf(e)==0)return b.substr(e.length)}return b},outputHtml:function(a,b){for(var c=KE.g[a].htmlTags,d=[],e=[],f=function(o,t,x,j){var q="";q+="<"+o;if(t)q+=t;if(x)q+=' style="'+x+'"';q+=j?" />":">";if(KE.browser.IsIE&&
j&&KE.util.inArray(o,["br","hr"]))q+="\n";d.push(q);j||e.push(o)},g=function(){if(e.length>0){var o=e.pop(),t="</"+o+">";if(KE.browser.IsIE&&KE.util.inArray(o,["p","div","table","ol","ul"]))t+="\n";d.push(t)}},h=function(o){o=o.childNodes;for(var t=0,x=o.length;t<x;t++){var j=o[t],q=false;switch(j.nodeType){case 1:var u=j.tagName.toLowerCase();if(typeof c[u]!="undefined"){for(var y="",n="",A=c[u],w=0,r=A.length;w<r;w++){var v=A[w];if(v=="/")q=true;else if(v.charAt(0)=="."){v=v.substr(1);for(var s=
v.split("-"),B="",z=0,C=s.length;z<C;z++)B+=z>0?s[z].charAt(0).toUpperCase()+s[z].substr(1):s[z];if(v=="border")if(j.style.border)n+="border:"+j.style.border+";";else{if(j.style.borderWidth&&j.style.borderStyle&&j.style.borderColor)n+="border:"+j.style.borderWidth+" "+j.style.borderStyle+" "+j.style.borderColor+";"}else if(v=="margin")if(j.style.margin)n+="margin:"+j.style.margin+";";else{if(j.style.marginLeft)n+="margin-left:"+j.style.marginLeft+";";if(j.style.marginRight)n+="margin-right:"+j.style.marginRight+
";";if(j.style.marginTop)n+="margin-top:"+j.style.marginTop+";";if(j.style.marginBottom)n+="margin-bottom:"+j.style.marginBottom+";"}else if(v=="padding")if(j.style.padding)n+="padding:"+j.style.padding+";";else{if(j.style.paddingLeft)n+="padding-left:"+j.style.paddingLeft+";";if(j.style.paddingRight)n+="padding-right:"+j.style.paddingRight+";";if(j.style.paddingTop)n+="padding-top:"+j.style.paddingTop+";";if(j.style.paddingBottom)n+="padding-bottom:"+j.style.paddingBottom+";"}else if(j.style[B])n+=
v+":"+j.style[B]+";"}else{s=j.getAttribute(v);if(v=="colspan"||v=="rowspan")if(s=="1")s=null;if(s!=null&&s!==""){if(typeof s=="string"&&s.match(/^javascript:/))s="";if(u=="a"&&v=="href"||u=="img"&&v=="src"||u=="embed"&&v=="src"){s=KE.util.removeDomain(a,s);s=s.replace(/&(?!amp;)/ig,"&amp;")}y+=" "+v+'="'+s+'"'}}}f(u,y,n,q)}if(j.hasChildNodes())h(j);else if(e.length>0){d[d.length-1].match(/^<p|^<div/)!=null&&d.push("&nbsp;");q||g()}break;case 3:d.push(KE.util.escape(j.nodeValue));break;default:break}}g()},
i=["script","style"],k=b.ownerDocument,m=0;m<i.length;m++)for(var p=k.getElementsByTagName(i[m]),l=0;l<p.length;l++)p[l].parentNode.removeChild(p[l]);h(b);return d.join("")},addClassName:function(a,b){if(!(a.className==b||a.className.indexOf(b+" ")==0))if(a.className.indexOf(" "+b)+b.length+1!=a.className.length)a.className+=" "+b},removeClassName:function(a,b){var c=a.className;if(c==b)a.className="";else if(c.indexOf(b+" ")==0)a.className=c.substring(c.indexOf(b+" "));else if(c.indexOf(" "+b)+b.length+
1==c.length)a.className=c.substring(0,c.indexOf(" "+b))},flag2Ubb:function(a){return a=a.replace(new RegExp('<img\\s[^>]*?max_editor_([^\\s>"]+)[^>]*?/?>',"ig"),function(b,c){var d=400,e=550,f;if(b.match(/width\s*:\s*(\d+)/i))e=b.match(/width\s*:\s*(\d+)/i)[1];else if(b.match(/width="?(\d+)/i))e=b.match(/width="?(\d+)/i)[1];if(b.match(/height\s*:\s*(\d+)/i))d=b.match(/height\s*:\s*(\d+)/i)[1];else if(b.match(/height="?(\d+)/i))d=b.match(/height="?(\d+)/i)[1];f=(f=b.match(/alt="?(.+?)(?=["\s>])/i))?
f[1]:"";b=(b=b.match(/\?max_autoplay=([truefalse]+)/i))?b[1]:"false";b=b.toLowerCase();return"["+c+"="+e+","+d+","+(b=="true"?"1":"0")+"]"+f+"[/"+c+"]"})},flag2Html:function(a){a=a.replace(new RegExp('<img\\s[^>]*?max_editor_([^\\s>"]+)[^>]*?/?>',"ig"),function(b,c){var d,e,f;e=(e=b.match(/width[=:][^\d]*(\d+)/i))?e[1]:540;d=(d=b.match(/height[=:][^\d]*(\d+)/i))?d[1]:400;f=(f=b.match(/alt="?(.+?)(?=["\s>])/i))?f[1]:"";b=(b=b.match(/\?max_autoplay=([truefalse]+)/i))?b[1]:"false";if(c=="flash")return String.format('<embed src="{0}" type="application/x-shockwave-flash" wmode="opaque" width="{1}" height="{2}" autostart="{3}" />',
f,e,d,b);if(c=="mp3"||c=="wma"||c=="wav"||c=="mid"||c=="wmv")return String.format('<embed src="{0}" type="application/x-mplayer2" width="{1}" height="{2}" autostart="{3}" />',f,e,d,b);if(c=="rm"||c=="rmvb"||c=="ra")return String.format('<embed src="{0}" type="audio/x-pn-realaudio-plugin" controls="ImageWindow,ControlPanel" width="{1}" height="{2}" autostart="{3}" />',f,e,d,b);return"["+c+""+(e?"="+e+","+d+",1":"")+"]"+f+"[/"+c+"]"});return a=a.replace(new RegExp("<(?:object|param).*?/?>","ig"),"")},
ubb2flag:function(a){function b(f,g){var h="editor_media.gif";if(f=="mp3"||f=="wma"||f=="wma"||f=="wmv"||f=="wav"||f=="mid")h="editor_audio.gif";else if(f=="ra"||f=="rm"||f=="rmvb")h="editor_real.gif";else if(f=="flash")h="editor_flash.gif";switch(f){case "mp3":case "wma":case "ra":case "mid":case "wav":d=true;break;default:d=false;break}return g=g.replace(new RegExp("\\["+f+"(.*?)]([\\s\\S]+?)\\[\\/"+f+"\\]","ig"),function(i,k,m){i=k?k.replace("=","").split(","):"";var p,l,o;if(i){if(i.length>0)p=
i[0];if(i.length>1)l=i[1];if(i.length>2)o=i[2]}p||(p=d?400:550);l||(l=d?64:400);o||(o=0);return'<img src="'+root+"/max-assets/images/blank.gif?max_autoplay="+(o=="1"?"true":"false")+'" class="max_editor_'+f+'" title="max_editor_'+f+'" alt="'+m+'" width="'+p+'" height="'+l+'"  style="border:solid 1px #aaaaaa; background-position:center center; background-repeat:no-repeat;background-image:url('+root+"/max-assets/images/"+h+')" />'})}for(var c=["mp3","wma","wmv","rm","ra","flash"],d=false,e=0;e<c.length;e++)a=
b(c[e],a);return a},html2Flag:function(a){var b=new RegExp('<embed\\s[^>]*?(?:src="[^>]*?\\.(?:swf|flv)"|application\\/x\\-shockwave\\-flash)[^>]*?/?>(?:</embed>)?',"ig"),c=new RegExp('<embed\\s[^>]*?(?:src="[^>]*?\\.(?:mp3|mid|wav|wma|avi)"|application\\/x-mplayer2)[^>]*?/?>(?:</embed>)?',"ig"),d=new RegExp('<embed\\s[^>]*?(?:src="[^>]*?\\.(?:rmvb|rm|ra)"|audio/x-pn-realaudio-plugin)[^>]*?/?>(?:</embed>)?',"ig"),e=new RegExp("<(?:object|param).*?/?>","ig"),f='<img src="'+root+'/max-assets/images/blank.gif?max_autoplay={5}" class="max_editor_{0}" title="max_editor_{0}" alt="{1}" width="{2}" height="{3}" style="border:solid 1px #aaaaaa; background-position:center center; background-repeat:no-repeat;background-image:url('+
root+'/max-assets/images/{4})" />';a=a.replace(b,function(g){var h=g.match(/width="(.*?)"/i),i=g.match(/height="(.*?)"/i),k=g.match(/src="(.*?)"/i);g=g.match(/autostart="(.+?)"/i);h=h?h[1]:400;i=i?i[1]:300;g=g?g[1]:"false";g=g.toLowerCase();if(g!="false"&&g!="true")g="false";k=k[1];return String.format(f,"flash",k,h,i,"editor_flash.gif",g)});a=a.replace(c,function(g){var h=g.match(/width="(.*?)"/i),i=g.match(/height="(.*?)"/i),k=g.match(/src="(.*?)"/i);g=g.match(/autostart="(.+?)"/i);h=h?h[1]:400;
i=i?i[1]:300;g=g?g[1]:"false";g=g.toLowerCase();if(g!="false"&&g!="true")g="false";k=k[1];return String.format(f,"mp3",k,h,i,"editor_audio.gif",g)});a=a.replace(d,function(g){var h=g.match(/width="(.*?)"/i),i=g.match(/height="(.*?)"/i),k=g.match(/src="(.*?)"/i);g=g.match(/autostart="(.+?)"/i);h=h?h[1]:400;i=i?i[1]:300;k=k[1];g=g?g[1]:"false";g=g.toLowerCase();if(g!="false"&&g!="true")g="false";return String.format(f,"rm",k,h,i,"editor_real.gif",g)});return a=a.replace(e,"")},html2Ubb:function(){}};
KE.layout={show:function(a,b){KE.layout.hide(a);KE.g[a].hideDiv.appendChild(b);KE.g[a].hideDiv.style.display="block";KE.g[a].layoutDiv=b},hide:function(a,b){var c=KE.g[a].layoutDiv;if(b)c.style.display="none";else try{KE.g[a].hideDiv.removeChild(c)}catch(d){}KE.g[a].hideDiv.style.display="none";KE.g[a].maskDiv.style.display="none";KE.util.focus(a)},make:function(){var a=KE.$$("div");a.style.position="absolute";a.style.zIndex=900;return a}};
KE.menu=function(a){function b(d,e){d=getRect(d);e.style.top=d.bottom+"px";e.style.left=d.left+"px"}this.arg=a;var c=KE.layout.make(a.id);c.className="ke-menu";a=KE.g[a.id].toolbarIcon[a.cmd];this.div=c;b(a,c);this.add=function(d,e){var f=KE.$$("div");f.className="ke-menu-noselected";f.style.width=this.arg.width;f.onmouseover=function(){this.className="ke-menu-selected"};f.onmouseout=function(){this.className="ke-menu-noselected"};f.onclick=e;f.innerHTML=d;this.append(f)};this.append=function(d){this.div.appendChild(d)};
this.insert=function(d){this.div.innerHTML=d};this.show=function(d){d&&b(d,this.div);KE.layout.show(this.arg.id,this.div)};this.picker=function(){var d=KE.lang.colorTable,e=KE.$$("table");e.cellPadding=0;e.cellSpacing=0;e.border=0;e.style.margin=0;e.style.padding=0;e.style.borderCollapse="separate";for(var f=0;f<d.length;f++)for(var g=e.insertRow(f),h=0;h<d[f].length;h++){var i=g.insertCell(h);i.className="ke-picker-cell";i.style.backgroundColor=d[f][h];i.title=d[f][h];i.onmouseover=function(){this.style.borderColor=
"#000000"};i.onmouseout=function(){this.style.borderColor="#F0F0EE"};i.onclick=new Function('KE.plugin["'+this.arg.cmd+'"].exec("'+this.arg.id+'", "'+d[f][h]+'")');i.innerHTML="&nbsp;"}this.append(e);this.show()}};
KE.toolbar={able:function(a,b){KE.each(KE.g[a].toolbarIcon,function(c,d){if(!KE.util.inArray(c,b)){KE.util.setOpacity(d,100);d.onclick=new Function('KE.util.click("'+a+'", "'+c+'")')}})},disable:function(a,b){KE.each(KE.g[a].toolbarIcon,function(c,d){if(!KE.util.inArray(c,b)){KE.util.setOpacity(d,50);d.onclick=null}})},create:function(a){KE.g[a].toolbarIcon=[];var b=KE.$$("table");b.oncontextmenu=function(){return false};b.onmousedown=function(){return false};b.onmousemove=function(){return false};
b.className="ke-toolbar";b.cellPadding=0;b.cellSpacing=0;b.border=0;var c=b.insertRow(0),d=c.insertCell(0);d.style.padding=0;d.style.margin=0;d.style.border=0;for(var e=KE.g[a].items.length,f=0,g=0;g<e;g++){var h=KE.g[a].items[g];if(g==0||h=="-"){var i=KE.$$("table");i.cellPadding=0;i.cellSpacing=0;i.border=0;i.className="ke-toolbar-table";c=i.insertRow(0);f=0;d.appendChild(i);if(h=="-")continue}i=c.insertCell(f);f++;var k=KE.$$("img");k.src=KE.g[a].skinsPath+"spacer.gif";KE.util.inArray(h,KE.g[a].defaultItems);
k.className="ke-common-icon ke-icon-"+h;k.alt=KE.lang[h];i.className="ke-icon";i.title=KE.lang[h];i.onmouseover=function(){this.className="ke-icon-selected"};i.onmouseout=function(){this.className="ke-icon"};i.onclick=new Function('KE.util.click("'+a+'", "'+h+'")');i.appendChild(k);KE.g[a].toolbarIcon[h]=i}return b}};KE.history={add:function(){},undo:function(a){KE.util.execCommand(a,"undo","")},redo:function(a){KE.util.execCommand(a,"redo","")}};
KE.remove=function(a,b){b=typeof b=="undefined"?0:b;var c=KE.g[a].container;b==1?document.body.removeChild(c):KE.$(a).parentNode.removeChild(c);KE.g[a].containner=null};
KE.create=function(a,b){if(KE.browser.IsIE)try{document.execCommand("BackgroundImageCache",false,true)}catch(c){}var d=KE.$(a);b=typeof b=="undefined"?0:b;if(!(b==0&&KE.g[a].container!=null)){var e=d.style.width,f=d.style.height,g=false,h;if(h=KE.$("ke_container_"+a))g=true;else h=KE.$$("div");var i=KE.$("ke_toolbar_"+a)||KE.toolbar.create(a),k=KE.$("ke_iframe_"+a)||KE.$$("iframe"),m=KE.$("ke_textarea_"+a)||KE.$$("textarea"),p=KE.$("ke_form_"+a)||KE.$$("div"),l=KE.$("ke_tab_"+a)||KE.$$("div"),o=KE.$("ke_bottom_"+
a)||KE.$$("table"),t=KE.$("ke_hide_"+a)||KE.$$("div"),x=KE.$("ke_mask_"+a)||KE.$$("div"),j=KE.$("ke_sizebox_"+a)||KE.$$("div"),q=KE.$("ke_sizebox_left_"+a)||KE.$$("a"),u=KE.$("ke_sizebix_right_"+a)||KE.$$("a");if(KE.browser.IsIE6||KE.browser.IsIE7)m.style.height=p.style.height;KE.util.setOpacity(x,50);x.className="ke-mask";t.style.display="none";if(g){l.tabItem_1=KE.$("ke_tab_item1_"+a);l.tabItem_2=KE.$("ke_tab_item2_"+a)}else{k.className="ke-iframe";k.style.border="none";h.id="ke_container_"+a;b==
1?document.body.appendChild(h):d.parentNode.insertBefore(h,d);h.appendChild(i);p.appendChild(k);p.appendChild(m);h.appendChild(p);h.appendChild(l);b=["\u53ef\u89c6\u5316","\u6e90\u4ee3\u7801"];for(var y=0;y<b.length;y++){var n=document.createElement("a");if(y==0){n.setAttribute("href","javascript:KE.util.setWyswygMode('"+a+"')");n.className="ke-tabitem-actived";l.tabItem_1=n}else{n.setAttribute("href","javascript:KE.util.setSourceMode('"+a+"')");l.tabItem_2=n}n.className="ke-tabitem-"+(y+1)+" "+n.className;
var A=document.createTextNode(b[y]);n.appendChild(A);l.appendChild(n)}j.className="ke-adjust";j.id="ke_sizebox_"+a;q.className="ke-adjust-del";q.id="ke_sizebox_left_"+a;u.className="ke-adjust-add";u.id="ke_sizebix_right_"+a;q.href='javascript:void(KE.util.shrink("'+a+'"));';u.href='javascript:void(KE.util.elongate("'+a+'"));';q.setAttribute("title",KE.lang.shrink);u.setAttribute("title",KE.lang.elongate);j.appendChild(q);j.appendChild(u);l.appendChild(j);q=o.insertRow(0);bottomLeft=q.insertCell(0);
bottomLeft.className="ke-bottom-left";u=KE.$$("img");u.className="ke-bottom-left-img";u.src=KE.g[a].skinsPath+"spacer.gif";bottomLeft.appendChild(u);bottomRight=q.insertCell(1);bottomRight.className="ke-bottom-right";document.body.appendChild(t);document.body.appendChild(x);h.className="ke-container";h.style.width=e;h.style.height=f;m.className="ke-textarea";m.style.display="none";p.className="ke-form";l.className="ke-tab"}if(KE.g[a].resizeMode!=2||KE.g[a].fullscreenMode)j.style.display="none";d.style.display=
"none";KE.util.setDefaultPlugin(a);e=k.contentWindow;var w=KE.util.getIframeDoc(k);f=KE.util.getFullHtml(a);if(!KE.browser.IsIE)w.designMode="On";w.open();w.write(f);w.close();if(KE.browser.IsIE)w.body.contentEditable="true";if(KE.g[a].autoOnsubmitMode){for(f=d.parentNode;f!=null&&f.tagName!="FORM";)f=f.parentNode;f!=null&&f.tagName=="FORM"&&KE.event.add(f,"submit",new Function('KE.util.setData("'+a+'")'))}KE.event.add(w,"click",new Function('KE.panel.hide("'+a+'");  KE.layout.hide("'+a+'")'));KE.event.add(m,
"click",new Function('KE.panel.hide("'+a+'") ;KE.layout.hide("'+a+'")'));KE.event.add(w,"keyup",new Function('KE.util.setActived("'+a+'");KE.history.add("'+a+'", true);'));KE.event.add(w,"mouseup",new Function('KE.util.setActived("'+a+'")'));if(KE.g[a].onCtrlEnter){KE.event.add(w,"keydown",function(r){KE.util.callCtrlEnter(a,r)});KE.event.add(m,"keydown",function(r){KE.util.callCtrlEnter(a,r)});KE.event.add(m,"keydown",new Function('KE.util.callCtrlEnter("'+a+'");'))}KE.event.add(m,"keyup",new Function('KE.history.add("'+
a+'", true)'));KE.g[a].container=h;KE.g[a].toolbarDiv=i;KE.g[a].formDiv=p;KE.g[a].tabDiv=l;KE.g[a].iframe=k;KE.g[a].newTextarea=m;KE.g[a].sizebox=j;KE.g[a].srcTextarea=d;KE.g[a].hideDiv=t;KE.g[a].bottomDiv=o;KE.g[a].maskDiv=x;KE.g[a].iframeWin=e;KE.g[a].iframeDoc=w;if(g){e=KE.g[a].width;f=KE.g[a].height}else{e=h.offsetWidth;f=h.offsetHeight;KE.g[a].width=e+"px"}KE.g[a].height=f+"px";g||KE.util.resize(a,e,f);setTimeout(function(){var r=d.value;if(r)if(KE.util.getCurrentMode(a)=="ubb"){r=ubb2html(r);
r=KE.util.html2Flag(r);if(window.beforeProcessUbbImg)r=window.beforeProcessUbbImg(r)}else{r=KE.util.html2Flag(r);if(window.beforeProcessImg)r=window.beforeProcessImg(r)}w.body.innerHTML=r;KE.util.pToBr(a);KE.history.add(a,false);if(!KE.g[a].wyswygMode){KE.g[a].wyswygMode=true;KE.util.setSourceMode(a)}},1);KE.g[a].isCreated=true}};KE.version="3.1.2";KE.scriptPath=KE.util.getScriptPath();KE.htmlPath=KE.util.getHtmlPath();KE.browser=KE.util.getBrowser();KE.plugin={};KE.g={};
KE.init=function(a){a.wyswygMode=typeof a.wyswygMode=="undefined"?true:a.wyswygMode;a.autoOnsubmitMode=typeof a.autoOnsubmitMode=="undefined"?true:a.autoOnsubmitMode;a.resizeMode=typeof a.resizeMode=="undefined"?2:a.resizeMode;a.filterMode=typeof a.filterMode=="undefined"?true:a.filterMode;a.skinType=a.skinType||"default";a.cssPath=a.cssPath||"";a.skinsPath=a.skinsPath||KE.scriptPath+"skins/";a.pluginsPath=a.pluginsPath||root+"/max-dialogs/editor/plugins/";a.minWidth=a.minWidth||200;a.minHeight=a.minHeight||
120;a.minChangeSize=a.minChangeSize||5;a.siteDomains=a.siteDomains||[];a.onCtrlEnter=a.onCtrlEnter||null;a.panelSize=a.panelSize||{width:600,height:360};var b=["source","preview","fullscreen","undo","redo","cut","copy","paste","plainpaste","wordpaste","justifyleft","justifycenter","justifyright","justifyfull","insertorderedlist","insertunorderedlist","indent","outdent","subscript","superscript","-","fontname","fontsize","textcolor","bgcolor","bold","italic","underline","strikethrough","removeformat",
"selectall","image","flash","media","layer","table","emoticons","link","unlink"];a.defaultItems=b;a.items=a.items||b;b={font:["color","size","face",".background-color"],span:[".color",".background-color",".font-size",".font-family",".font-weight",".font-style",".text-decoration",".vertical-align"],div:["class","align",".border",".margin",".padding",".text-align",".color",".background-color",".font-size",".font-family",".font-weight",".font-style",".text-decoration",".vertical-align"],a:["href","target"],
embed:["src","type","loop","wmode","autostart","quality",".width",".height","/"],img:["src","width","height","border","alt","title",".width",".height","/"],hr:["/"],br:["/"],p:["align",".text-align",".color",".background-color",".font-size",".font-family",".font-weight",".font-style",".text-decoration",".vertical-align"],table:["border","cellspacing","cellpadding","width","height",".padding",".margin",".border",".width",".height"],tbody:[],tr:[],td:["align","rowspan","colspan","width","height",".text-align",
".color",".background-color",".font-size",".font-family",".font-weight",".font-style",".text-decoration",".vertical-align"],th:["align","rowspan","colspan","width","height",".text-align",".color",".background-color",".font-size",".font-family",".font-weight",".font-style",".text-decoration",".vertical-align"],strong:[],b:[],ol:["align",".text-align",".color",".background-color",".font-size",".font-family",".font-weight",".font-style",".text-decoration",".vertical-align"],ul:["align",".text-align",
".color",".background-color",".font-size",".font-family",".font-weight",".font-style",".text-decoration",".vertical-align"],li:["align",".text-align",".color",".background-color",".font-size",".font-family",".font-weight",".font-style",".text-decoration",".vertical-align"],sub:[],sup:[],blockquote:["align",".text-align",".color",".background-color",".font-size",".font-family",".font-weight",".font-style",".text-decoration",".vertical-align"],h1:["align",".text-align",".color",".background-color",
".font-size",".font-family",".font-weight",".font-style",".text-decoration",".vertical-align"],h2:["align",".text-align",".color",".background-color",".font-size",".font-family",".font-weight",".font-style",".text-decoration",".vertical-align"],h3:["align",".text-align",".color",".background-color",".font-size",".font-family",".font-weight",".font-style",".text-decoration",".vertical-align"],h4:["align",".text-align",".color",".background-color",".font-size",".font-family",".font-weight",".font-style",
".text-decoration",".vertical-align"],h5:["align",".text-align",".color",".background-color",".font-size",".font-family",".font-weight",".font-style",".text-decoration",".vertical-align"],h6:["align",".text-align",".color",".background-color",".font-size",".font-family",".font-weight",".font-style",".text-decoration",".vertical-align"],em:[],u:[],strike:[]};a.htmlTags=a.htmlTags||b;KE.g[a.id]=a;KE.g[a.id].undoStack=[];KE.g[a.id].redoStack=[];KE.util.loadStyle(a.skinsPath+a.skinType+".css")};
KE.show=function(a){KE.init(a);KE.event.add(window,"load",new Function('KE.create("'+a.id+'")'))};
KE.plugin.fullscreen={resetFull:function(a){var b=max.global.getBrowserRect(),c=KE.g[a].container;c.style.left="0px";c.style.top="0px";c.style.zIndex=49;KE.util.resize(a,b.width,b.height)},ubbClick:function(a){this.click(a)},click:function(a){var b=KE.g[a],c=b.container,d=c.style,e=function(){b.fullscreenMode&&KE.plugin.fullscreen.resetFull(a)};if(b.fullscreenMode){b.fullscreenMode=false;d.position="static";document.body.parentNode.style.overflow="auto";KE.util.resize(a,"100%",parseInt(this.height));
KE.event.remove(window,"resize",e);if(KE.browser.IsIE6){for(var f=this.dropDownList,g=0;g<f.length;g++){var h=f[g];h.obj.style.display=h.disp}this.dropDownList=f=null}}else{if(KE.browser.IsIE6){this.dropDownList=[];f=document.getElementsByTagName("select");for(g=0;g<f.length;g++){h={};h.obj=f[g];h.disp=f[g].style.display+"";f[g].style.display="none";this.dropDownList.push(h)}}document.body.parentNode.style.overflow="hidden";b.fullscreenMode=true;this.width=c.offsetWidth;this.height=c.offsetHeight;
KE.util.hideBottom(a);d.position="absolute";this.resetFull(a);KE.event.add(window,"resize",e)}}};KE.plugin.bgcolor={click:function(a){KE.util.selection(a);(new KE.menu({id:a,cmd:"bgcolor"})).picker()},exec:function(a,b){KE.util.select(a);KE.browser.IsIE?KE.util.execCommand(a,"backcolor",b):KE.util.execCommand(a,"hiliteColor",b);KE.layout.hide(a);KE.util.focus(a)}};
KE.plugin.fontname={click:function(a){KE.util.selection(a);var b=KE.lang.fontTable,c=new KE.menu({id:a,cmd:"fontname",width:"160px"});KE.each(b,function(d,e){c.add('<span style="font-family: '+d+';">'+e+"</span>",new Function('KE.plugin["fontname"].exec("'+a+'", "'+d+'")'))});c.show()},exec:function(a,b){KE.util.select(a);KE.util.execCommand(a,"fontname",b);KE.layout.hide(a);KE.util.focus(a)}};
KE.plugin.fontsize={click:function(a){KE.util.selection(a);var b=new KE.menu({id:a,cmd:"fontsize",width:"100px"});KE.each({"1":"1\u53f7","2":"2\u53f7","3":"3\u53f7","4":"4\u53f7","5":"5\u53f7","6":"6\u53f7","7":"7\u53f7"},function(c,d){b.add('<font size="'+c+'">'+d+"</font>",new Function('KE.plugin["fontsize"].exec("'+a+'", "'+c+'")'))});b.show()},exec:function(a,b){KE.util.select(a);KE.util.execCommand(a,"fontsize",b.substr(0,1));KE.layout.hide(a);KE.util.focus(a)}};
KE.plugin.source={click:function(a){obj.wyswygMode?setSourceMode(a):setWyswygMode(a)}};KE.plugin.textcolor={click:function(a){KE.util.selection(a);(new KE.menu({id:a,cmd:"textcolor"})).picker()},exec:function(a,b){KE.util.select(a);KE.util.execCommand(a,"forecolor",b);KE.layout.hide(a);KE.util.focus(a)}};
KE.plugin.layer={click:function(a){var b=["margin:5px;border:1px solid #000000;","margin:5px;border:2px solid #000000;","margin:5px;border:1px dashed #000000;","margin:5px;border:2px dashed #000000;","margin:5px;border:1px dotted #000000;","margin:5px;border:2px dotted #000000;"];KE.util.selection(a);for(var c=new KE.menu({id:a,cmd:"layer",width:"150px"}),d=0;d<b.length;d++)c.add('<div style="height:15px;'+b[d]+'"></div>',new Function('KE.plugin["layer"].exec("'+a+'", "padding:5px;'+b[d]+'")'));c.show()},
exec:function(a,b){KE.util.select(a);KE.util.insertContent(a,'<div style="'+b+'">'+KE.lang.pleaseInput+"</div>");KE.layout.hide(a);KE.util.focus(a)}};
KE.plugin.table={selected:function(a,b,c){var d=b.toString(10)+" x "+c.toString(10)+" \u8868\u683c";KE.$("tableLocation"+a).innerHTML=d;for(d=1;d<=10;d++)for(var e=1;e<=10;e++)KE.$("tableTd"+a+d.toString(10)+"_"+e.toString(10)+"").style.backgroundColor=d<=b&&e<=c?"#eeeeee":"#FFFFFF"},click:function(a){KE.util.selection(a);for(var b='<table cellpadding="0" cellspacing="0" border="0" style="width:120px;margin:1px 0 0 1px;border-collapse:collapse;">',c=1;c<=10;c++){b+="<tr>";for(var d=1;d<=10;d++){var e=
c.toString(10)+","+d.toString(10);b+='<td id="tableTd'+a+c.toString(10)+"_"+d.toString(10)+'" style="font-size:0;width:12px;height:12px;border:1px solid #ccc;cursor:pointer;" onclick="javascript:KE.plugin[\'table\'].exec(\''+a+"', '"+e+"');\" onmouseover=\"javascript:KE.plugin['table'].selected('"+a+"', '"+c.toString(10)+"', '"+d.toString(10)+"');\">&nbsp;</td>"}b+="</tr>"}b+='<tr><td colspan="10" id="tableLocation'+a+'" style="text-align:center;height:20px;margin:0;padding:0;border:0;color:#999;"></td></tr>';
b+="</table>";a=new KE.menu({id:a,cmd:"table"});a.insert(b);a.show()},ubbClick:function(a){this.click(a)},exec:function(a,b){KE.util.select(a);b=b.split(",");for(var c='<table border="1">',d=0;d<b[0];d++){c+="<tr>";for(var e=0;e<b[1];e++)c+="<td>&nbsp;</td>";c+="</tr>"}c+="</table>";KE.util.insertContent(a,c);KE.layout.hide(a);KE.util.focus(a)}};
KE.plugin.emoticons={menu:null,click:function(a){KE.util.selection(a);var b="";if(KE.g[a].action)b+="&action="+KE.g[a].action;if(KE.g[a].targetID)b+="&targetid="+KE.g[a].targetID;KE.panel.show(a,"emoticons",417,310,b)},ubbClick:function(a){this.click(a)}};KE.panel={};
KE.panel.show=function(a,b,c,d,e){if(d==-1)d=KE.g[a].panelSize.height;if(c==-1)c=KE.g[a].panelSize.width;KE.util.selection(a);if(KE.panel[a]==null)KE.panel[a]={};if(KE.panel[a].popup==null)KE.panel[a].popup={};var f=KE.panel[a].popup[b];if(!f){f=KE.$("ME_"+b);var g=addElement("div");g.className="ke-menu";g.id="ME_popup_"+b;f=new popup(g,f,false,null,"left bottom");f.maskDialog=1;g.style.zIndex=50;var h=root+"/max-dialogs/editor/"+b+".aspx?id="+a;if(window.forumID)h+="&forumid="+forumID;if(e)h+=e;
e=document.createElement("iframe");e.setAttribute("scrolling","no");e.setAttribute("frameBorder","0");e.style.border="none";g.appendChild(e);try{g='<body style="width:100%;height:100%;background:url('+root+'/max-templates/default/images/ajaxloading_big.gif) no-repeat 50% 45%;">&nbsp;</body>';var i=KE.util.getIframeDoc(e);i.open();i.write(g);i.close()}catch(k){}if(c)e.width=c;if(d)e.height=d;e.src=h;KE.panel[a].popup[b]=f;f.show()}};
KE.panel.hide=function(a,b){if(a=KE.panel[a])if(a=a.popup)if(b)(b=a[b])&&b.hide();else for(var c in a)a[c].hide()};KE.plugin.insertorderedlist={click:function(a){if(KE.browser.IsIE){var b=KE.g[a].iframeDoc;KE.util.selection(a);a=b.selection.createRange();var c=a.htmlText.split(/<br\s*\/?>/ig);b="<ol>";for(var d=0;d<c.length;d++)b+="<li>"+c[d]+"</li>";b+="</ol>";a.pasteHTML(b)}else KE.util.execCommand(a,"insertorderedlist",null)},ubbClick:function(){}};
KE.plugin.insertunorderedlist={click:function(a){if(KE.browser.IsIE){var b=KE.g[a].iframeDoc;KE.util.selection(a);a=b.selection.createRange();var c=a.htmlText.split(/<br\s*\/?>/ig);b="<ul>";for(var d=0;d<c.length;d++)b+="<li>"+c[d]+"</li>";b+="</ul>";a.pasteHTML(b)}else KE.util.execCommand(a,"insertunorderedlist",null)},ubbClick:function(){}};
function ubb2html(a){var b;a=a;a=a.replace(/&(?![a-z]{2,4};)/ig,"&amp;");a=a.replace(/</g,"&lt;");a=a.replace(/</g,"&lt;");a=a.replace(/>/g,"&gt;");a=a.replace(/\x20/g,"&nbsp;");a=a.replace(/\[quote\](?:\r?\n)+/ig,"[quote]\r\n");a=a.replace(/(?:\r?\n)+\[\/quote\]/ig,"\r\n[/quote]");a=a.replace(/\r?\n/g,"<br />");a=a.replace(/\[code\](.*?)\[\/code\]/ig,function(f,g){f=g.replace(/\[/g,"{[}");f=f.replace(/\]/g,"{]}");return f="[code]"+f+"[/code]"});a=a.replace(/\[(\/?)(b|u|s|sup|sub)\]/ig,"<$1$2>");
a=a.replace(/\[(\/?)i\]/ig,"<$1em>");b=/\[color\s*=\s*([^\]]+?)\](.*?)\[\/color\]/ig;for(var c=/\[font\s*=\s*([^\]]+?)\](.*?)\[\/font\]/ig,d=/\[size\s*=\s*([^\]]+?)\](.*?)\[\/size\]/ig,e=/\[bgcolor\s*=\s*([^\]]+?)\](.*?)\[\/bgcolor\]/ig;a.match(b);)a=a.replace(b,'<font color="$1">$2</font>');for(;a.match(c);)a=a.replace(c,'<font face="$1">$2</font>');for(;a.match(d);)a=a.replace(d,function(f,g,h){if(/\d+$/.test(g))return'<font size="'+g+'">'+h+"</font>";return'<span style="font-size:'+g+'">'+h+"</span>"});
for(;a.match(e);)a=a.replace(e,'<span style="background-color:$1;">$2</span>');for(b=0;b<3;b++)a=a.replace(/\[align\s*=\s*([^\]]+?)\](((?!\[align(?:\s+[^\]]+)?\])[\s\S])*?)\[\/align\](?:<br\s*\/?>)?/ig,'<div style="text-align:$1">$2</div>');if(window.beforeProcessUbbImg)a=window.beforeProcessUbbImg(a);a=a.replace(/\[img\]\s*([\s\S]+?)\s*\[\/img\]/ig,'<img src="$1" />');a=a.replace(/\[img\s*=\s*(\d+),(\d+)\s*\]\s*([\s\S]+?)\s*\[\/img\]/ig,'<img src="$3" width="$1" height="$2" />');a=a.replace(/\[url\]\s*([\s\S]+?)\s*\[\/url\]/ig,
'<a href="$1">$1</a>');a=a.replace(/\[url\s*=\s*([^\]\s]+?)\s*\]\s*([\s\S]+?)\s*\[\/url\]/ig,'<a href="$1">$2</a>');a=a.replace(/\[email\]\s*([\s\S]+?)\s*\[\/email\]/ig,'<a href="mailto:$1">$1</a>');a=a.replace(/\[email\s*=\s*([^\]\s]+?)\s*\]\s*([\s\S]+?)\s*\[\/email\]/ig,'<a href="mailto:$1">$2</a>');a=a.replace(/\[indent\]([\s\S]*?)\[\/indent\]/ig,"<blockquote>$1</blockquote>");a=KE.util.ubb2flag(a);a=a.replace(/\[table(?:\s*=\s*(\d{1,4}%?)\s*(?:,\s*([^\]]+)\s*)?)?]/ig,function(f,g,h){f="<table";
if(g)f+=' width="'+g+'"';if(h)f+=' bgcolor="'+h+'"';return f+' border="1">'});a=a.replace(/\[tr(?:\s*=(\s*[^\]]+))?\]/ig,function(f,g){return"<tr"+(g?' bgcolor="'+g+'"':"")+">"});a=a.replace(/\[td\s*=\s*([\d,]+)\]/ig,function(f,g){f=g.split(",");g="<td";if(f.length==1)g+=' width="'+f[0]+'"';else if(f.length>1){g+=' colspan="'+f[0]+'"';g+=' rowspan="'+f[1]+'"';if(f.length>2)g+=' width="'+f[2]+'"'}return g+">"});a=a.replace(/\[(table|tr|td)\]/ig,"<$1>");a=a.replace(/\[\/?(table|tr|td)\]/ig,"</$1>");
a=a.replace(/\s*\[\*\](.*?)<br\s*\/?>/ig,"<li>$1</li>");for(b=/\[list(.*?)\](.*?)\[\/list\]/ig;a.match(b);)a=a.replace(b,function(f,g,h){if(g&&g=="=1")return"<ol>"+h+"</ol>";return"<ul>"+h+"</ul>"});a=a.replace(/\{\[\}/g,"[");a=a.replace(/\{\]\}/g,"]");if(window.emoticon2Html)a=emoticon2Html(a);return a}var mapSize={};mapSize["xx-small"]="1";mapSize.small="3";mapSize.medium="4";mapSize["x-small"]="2";mapSize.large="5";mapSize["x-large"]="6";mapSize["xx-large"]="7";mapSize["6pt"]="1";
mapSize["6.5pt"]="1";mapSize["7pt"]="1";mapSize["8pt"]="2";mapSize["9pt"]="2";mapSize["10pt"]="2";mapSize["11pt"]="2";mapSize["12pt"]="3";mapSize["13pt"]="3";mapSize["14pt"]="4";mapSize["15pt"]="4";mapSize["16pt"]="4";mapSize["17pt"]="5";mapSize["18pt"]="5";mapSize["19pt"]="5";mapSize["20pt"]="6";mapSize["21pt"]="6";mapSize["22pt"]="6";mapSize["24pt"]="6";mapSize["25pt"]="7";mapSize["36pt"]="7";mapSize["7px"]="1";mapSize["9px"]="1";mapSize["10px"]="1";mapSize["11px"]="1";mapSize["12px"]="1";
mapSize["13px"]="1";mapSize["14px"]="2";mapSize["15px"]="2";mapSize["16px"]="2";mapSize["17px"]="3";mapSize["18px"]="3";mapSize["19px"]="3";mapSize["20px"]="4";mapSize["21px"]="4";mapSize["22px"]="4";mapSize["23px"]="5";mapSize["24px"]="5";mapSize["25px"]="5";mapSize["26px"]="6";mapSize["27px"]="6";mapSize["28px"]="6";mapSize["36px"]="7";
function HtmlTagBase(a){this.attributes={};this.Pair=null;this.EndUbb=this.StartUbb="";this.Styles={};this.isBlockTag=false;this.TagName=a.tagName;var b=a.attributes,c=b.length,d,e;for(a=0;a<c;a++){d=b.item(a);e=d.nodeName;if(d=d.value){if(e.indexOf("color")>=0)d=Util.ConvertRGB(d);if(e=="src"||e=="href"){d=d.replace(/\[/g,"%5B");d=d.replace(/\]/g,"%5D")}this.attributes[e]=d}}if(this.attributes.style){b=(this.attributes.style+"").split(";");for(a=0;a<b.length;a++){d=b[a].split(":");if(d.length==2){c=
d[0].trim().toLowerCase();if(!this.Styles[c]){d=d[1].trim().trim("'");if(c.indexOf("color")>=0)d=Util.ConvertRGB(d);this.Styles[c]=d}}}}}
function HasStyleTag(a){function b(){var c="",d="";if(this.Styles.color){c+="[color="+this.Styles.color+"]";d="[/color]"+d}if(this.Styles["font-size"]){var e=this.Styles["font-size"].toString();mapSize[e]||(e=e.replace(/(\d+)\.\d+(\D+)/,"$1$2"));c+="[size="+mapSize[e]+"]";d="[/size]"+d}if(this.Styles["font-family"]){c+="[font="+this.Styles["font-family"]+"]";d="[/font]"+d}if(this.Styles["font-style"])if(this.Styles["font-style"]+""=="italic"){c+="[i]";d="[/i]"+d}if(this.Styles["font-weight"])if(this.Styles["font-weight"]+
""!="normal"){c+="[b]";d="[/b]"+d}if(this.Styles["text-decoration"]){e=this.Styles["text-decoration"]+"";if(e=="underline"){c+="[u]";d="[/u]"+d}else if(e=="line-through"){c+="[s]";d="[/s]"+d}}if(this.Styles["text-align"]){e=this.Styles["text-align"].toString();if(e=="left"||e=="right"||e=="center"){c+="[align="+e+"]";d="[/align]"+d}}if(this.Styles["background-color"]){c+="[bgcolor="+this.Styles["background-color"]+"]";d="[/bgcolor]"+d}this.StartUbb=c;this.EndUbb=d}HtmlTagBase.call(this,a);b.call(this)}
function PairTag(a){HtmlTagBase.call(this,a);this.UbbTag=this.TagName;this.StartUbb="["+this.UbbTag+"]";this.EndUbb="[/"+this.UbbTag+"]"}function TdTag(a){HtmlTagBase.call(this,a);var b,c;a=this.attributes.width;b=this.attributes.colspan;c=this.attributes.rowspan;var d="[td";if((b||c)&&(c!="1"||c!="1")){d+="="+(b?b:"1")+","+(c?c:"1");if(a)d+=","+a}else if(a)d+="="+a;this.StartUbb=d+"]";this.EndUbb="[/td]"}
function ImgTag(a){HtmlTagBase.call(this,a);var b=a=0,c=this.Styles.width||this.attributes.width,d=this.Styles.height||this.attributes.height;if(c)a=parseInt(c);if(d)b=parseInt(d);c="[img";if(a>0){c+="="+a;if(b>0)c+=","+b}c+="]"+this.attributes.src+"[/img]";this.StartUbb=c}
function ATag(a){var b=/^#+$/;HtmlTagBase.call(this,a);this.Href=this.attributes.href;a=false;if(!this.Href||b.test(this.Href.trim()))a=true;if(a)this.EndUbb=this.StartUbb="";else if(this.Href.indexOf("mailto:")>-1){b=this.Href.indexOf("mailto:")+7;this.Href=this.Href.substr(b,this.Href.length-b);this.StartUbb="[email="+this.Href+"]";this.EndUbb="[/email]"}else{this.StartUbb="[url="+this.Href+"]";this.EndUbb="[/url]"}}
function FontTag(a){HasStyleTag.call(this,a);if(this.attributes.color){this.StartUbb+="[color="+this.attributes.color+"]";this.EndUbb="[/color]"+this.EndUbb}if(this.attributes.size){a=this.attributes.size;this.StartUbb+="[size="+(mapSize[a]?mapSize[a].toString():a)+"]";this.EndUbb="[/size]"+this.EndUbb}if(this.attributes.face){this.StartUbb+="[font="+this.attributes.face+"]";this.EndUbb="[/font]"+this.EndUbb}}function SpanTag(a){HasStyleTag.call(this,a)}
function BrTag(a){HtmlTagBase.call(this,a);this.StartUbb="\r\n"}function DivTag(a){HasStyleTag.call(this,a);if(this.attributes.align){this.StartUbb="[align="+this.attributes.align+"]"+this.StartUbb;this.EndUbb+="[/align]"}this.isBlockTag=true}function PTag(a){HasStyleTag.call(this,a);if(this.attributes.align){this.StartUbb="[align="+this.attributes.align+"]"+this.StartUbb;this.EndUbb+="[/align]"}this.isBlockTag=true}
function Center(a,b,c,d){HtmlTagBase.call(this,d);this.StartUbb="[align=center]";this.EndUbb="[/align]"}function TableTag(a){HtmlTagBase.call(this,a);a="[table";a+="]";this.StartUbb=a;this.EndUbb="[/table]"}function LiTag(a){HtmlTagBase.call(this,a);this.StartUbb="[*]";this.EndUbb="\r\n"}function ListTag(a){HtmlTagBase.call(this,a);this.EndUbb="[/list]";a="[list";if(this.TagName=="ol")a+="=1";else if(this.Styles["list-style-type"]=="decimal")a+="=1";a+="]";this.StartUbb=a}
function HTag(a){HtmlTagBase.call(this,a);a=parseInt(this.TagName.substring(1));a=7-a;this.StartUbb="[size="+a+"][b]";this.EndUbb="[/b][/size]"}
function EmbedTag(a){HtmlTagBase.call(this,a);Src=this.attributes.src+"";a=/\.(\w+)\s*$/g;this.Type=this.attributes.type+"";width=550;isNaN(this.attributes.width)||(width=parseInt(this.attributes.width));var b=400;isNaN(this.attributes.height)||(b=parseInt(this.attributes.height));AutoStart=false;if(this.attributes.autostart){var c=this.attributes.autostart.toString();if(c=="1"||c=="true")AutoStart=true}var d=c="";if(a.test(Src))c=a.exec(Src)[1];switch(Type){case "application/x-shockwave-flash":d=
"flash";break;case "application/x-mplayer2":d="wmv";switch(c){case "mp3":case "wav":case "wma":case "midi":d="mp3";break}break;case "audio/x-pn-realaudio-plugin":d="rm";switch(c){case "ra":d="rm";break}break}this.StartUbb=d?String.format("[{0}={3},{4},{2}]{1}[/{0}]",d,Src,this.AutoStart?"1":"0",width,b):""}
var Util=new (function(){this.ConvertRGB=function(a){return a.replace(new RegExp("rgb\\s*\\(\\s*(\\d+),\\s*(\\d+),\\s*(\\d+)\\s*\\)","ig"),function(b,c,d,e){b=parseInt(c).toString(16);if(b.length<2)b="0"+b;d=parseInt(d).toString(16);if(d.length<2)d="0"+d;e=parseInt(e).toString(16);if(e.length<2)e="0"+e;return"#"+b+d+e})}}),factoryUbbTag=function(a,b,c,d,e){a=null;switch(b.toLowerCase()){case "font":a=new FontTag(e);break;case "span":a=new SpanTag(e);break;case "ol":case "ul":a=new ListTag(e);break;
case "li":a=new LiTag(e);break;case "blockquote":a=new PairTag(e);a.StartUbb="[indent]";a.EndUbb="[/indent]";break;case "div":a=new DivTag(e);break;case "table":a=new TableTag(e);break;case "a":a=new ATag(e);break;case "img":a=new ImgTag(e);break;case "p":a=new PTag(e);break;case "td":case "th":a=new TdTag(e);break;case "tr":a=new PairTag(e);break;case "br":a=new BrTag(e);break;case "s":case "b":case "i":case "sub":case "sup":case "u":a=new PairTag(e);break;case "strong":a=new PairTag(e);a.StartUbb=
"[b]";a.EndUbb="[/b]";break;case "em":a=new PairTag(e);a.StartUbb="[i]";a.EndUbb="[/i]";break;case "strike":a=new PairTag(e);a.StartUbb="[s]";a.EndUbb="[/s]";break;case "h1":case "h2":case "h3":case "h4":case "h5":case "h6":a=new HTag(e);break;case "embed":a=new EmbedTag(e);break}return a},UbbConverter=new (function(){this.ConvertToUbb=function(a){var b=new RegExp("<style.*?>.*?</style>","ig"),c=new RegExp("<script[^>]*?>.*?<\/script>","ig");a=a.replace(/\n/g,"");a=a.replace(/\r/g,"");a=a.replace(c,
"");a=a.replace(b,"");a=a.replace(/&nbsp;/ig," ");a=a.replace(/&(?!amp;)/ig,"&amp;");a=a.trim();a='<?xml version="1.0"?><root>'+a+"</root>";var d;if(KE.browser.IsIE){try{d=new ActiveXObject("Msxml2.DOMDocument")}catch(e){d=new ActiveXObject("Msxml.DOMDocument")}d.loadXML(a)}else d=(new DOMParser).parseFromString(a,"text/xml");var f=[],g=0,h=false;g=0;var i=function(k){if(k.nodeType==1){var m=factoryUbbTag(g++,k.tagName,"",0,k);if(m!=null){m.isBlockTag&&g>0&&h==false&&f.push("\r\n");f.push(m.StartUbb)}if(k.childNodes.length>
0)for(var p=k.childNodes.length,l=0;l<p;l++)i(k.childNodes[l]);if(m!=null){f.push(m.EndUbb);m.isBlockTag&&f.push("\r\n");h=m.isBlockTag}g++}else k.nodeType==3&&f.push(k.nodeValue)};a=d.getElementsByTagName("root")[0];i(a);a=f.join("");a=a.replace(/&amp;/ig,"&");a=a.replace(/&gt;/ig,">");return a=a.replace(/&lt;/ig,"<")}});
function html2ubb(a){a=KE.util.html2Flag(a);a=KE.util.flag2Ubb(a);if(window.emoticon2Ubb)a=emoticon2Ubb(a);if(window.beforeProcessImg)a=window.beforeProcessImg(a);a=UbbConverter.ConvertToUbb(a);a=a.replace(/\[quote\](?:\r?\n)+/ig,"[quote]\r\n");return a=a.replace(/(?:\r?\n)+\[\/quote\]/ig,"\r\n[/quote]")};
