ALTER TABLE bx_UserProps ADD CONSTRAINT FK_bx_UserProps_PropID FOREIGN KEY (PropID) REFERENCES bx_Props (PropID) ON UPDATE CASCADE ON DELETE CASCADE 

ALTER TABLE bx_UserProps ADD CONSTRAINT FK_bx_UserProps_UserID FOREIGN KEY (UserID) REFERENCES bx_Users (UserID) ON UPDATE CASCADE ON DELETE CASCADE
